package at.fhv.itm3.s2.roundabout.api.entity;

public enum ConsumerType {
    ROUNDABOUT_INLET, ROUNDABOUT_EXIT, ROUNDABOUT_SECTION, STREET_SECTION, INTERSECTION,
    PREDESTRIAN_STREET_SECTION, PREDESTRIAN_CROSSING, PREDESTRIAN_WAITING_AREA_CROSSING

}
